### ISSUE TITLE
App not working after the Affliction patch

### ISSUE THREAD

**Issue by kartelusm** [C1rdec/Poe-Lurker#407]
App not working after the affliction patch. It starts, the home button is visible and functional, but the trade requests are not triggering the overlay.

I tried several other apps (not maintained, but were working earlier today, before the patch) and none works as intended.

Perhaps GGG changed something, I am not sure. The game is standardly in a windowed fullscreen mode.

**Comment by TactfulRanger** [comment]
Same here. Something has changed since the patch.

**Comment by C1rdec** [comment]
Yeah on it...

**Comment by C1rdec** [comment]
1.23.1 should fix

**Comment by C1rdec** [comment]
Basically we lost the @from and @to keyword from the message in `client.txt`.

I manage to parse the new format but since I cannot tell if the message is receive or sent Poe Lurker will think that you receive and offer when you want to buy items..

I created a [Reddit Post](https://www.reddit.com/r/pathofexile/comments/18e5miy/all_trade_tool_broken/) and wrote a message in the Dev Channel of Poe Discord

**Comment by C1rdec** [comment]
GGG fixed the issue

**Comment by kartelusm** [comment]
@C1rdec thank you for alerting them, and thank you for the app
